// angular/lib/projects/uniswap-angular/src/lib/uniswap-angular-swapper/components/approval/approval.component.ts
import { Component, Input } from '@angular/core';
import {
  TransactionStatus,
  UniswapDappSharedLogic,
} from 'uniswap-dapp-integration-shared';

@Component({
  selector: 'lib-approval',
  templateUrl: './approval.component.html',
  styleUrls: ['./approval.component.scss'],
})
export class ApprovalComponent {
  @Input() public uniswapDappSharedLogic!: UniswapDappSharedLogic;

  public transactionStatus = TransactionStatus;
  constructor() {}
}

<button
  width="100%"
  class="uni-ic__swap-allow uni-ic__theme-background-button"
  *ngIf="
    uniswapDappSharedLogic.tradeContext?.approvalTransaction &&
    uniswapDappSharedLogic.tradeContext?.fromBalance?.hasEnough
  "
  (click)="uniswapDappSharedLogic.approveAllowance()"
>
  <div class="uni-ic__swap-allow-container">
    <span style="display: flex; align-items: center">
      <img
        *ngIf="!uniswapDappSharedLogic.inputToken.tokenImageContext.isSvg"
        [src]="uniswapDappSharedLogic.inputToken.tokenImageContext.image"
        class="uni-ic__swap-allow-icon"
      />
      <span
        *ngIf="
          uniswapDappSharedLogic.miningTransaction === undefined ||
          uniswapDappSharedLogic.miningTransaction?.status ===
            transactionStatus.rejected
        "
        >Allow the Uniswap Protocol to use your
        {{ uniswapDappSharedLogic.tradeContext!.fromToken.symbol }}</span
      >
      <span
        *ngIf="
          uniswapDappSharedLogic.miningTransaction?.status ===
          transactionStatus.waitingForConfirmation
        "
        >Waiting for confirmation....</span
      >
      <span
        *ngIf="
          uniswapDappSharedLogic.miningTransaction?.status ===
          transactionStatus.mining
        "
        >Waiting for your transaction to be mined...</span
      >
    </span>
    <div class="uni-ic__swap-allow-info">
      <div>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="20"
          height="20"
          viewBox="0 0 24 24"
          fill="none"
          stroke="white"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <circle cx="12" cy="12" r="10"></circle>
          <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"></path>
          <line x1="12" y1="17" x2="12.01" y2="17"></line>
        </svg>
      </div>
    </div>
  </div>
</button>

// react-package/package/src/components/approval.tsx
import React from 'react';
import {
  TransactionStatus,
  UniswapDappSharedLogic,
} from 'uniswap-dapp-integration-shared';

const Approval = ({
  uniswapDappSharedLogic,
}: {
  uniswapDappSharedLogic: UniswapDappSharedLogic;
}): JSX.Element => {
  const transactionStatus = TransactionStatus;

  return (
    <div>
      {uniswapDappSharedLogic.miningTransaction?.status}
      {uniswapDappSharedLogic.tradeContext?.approvalTransaction &&
        uniswapDappSharedLogic.tradeContext?.fromBalance?.hasEnough && (
          <button
            style={{ width: '100%' }}
            className="uni-ic__swap-allow uni-ic__theme-background-button"
            onClick={() => uniswapDappSharedLogic.approveAllowance()}
          >
            <div className="uni-ic__swap-allow-container">
              <span style={{ display: 'flex', alignItems: 'center' }}>
                {!uniswapDappSharedLogic.inputToken.tokenImageContext.isSvg && (
                  <img
                    src={
                      uniswapDappSharedLogic.inputToken.tokenImageContext.image
                    }
                    className="uni-ic__swap-allow-icon"
                  />
                )}
                {(uniswapDappSharedLogic.miningTransaction === undefined ||
                  uniswapDappSharedLogic.miningTransaction.status ===
                    transactionStatus.rejected) && (
                  <span>
                    You must give the Uniswap smart contract permisson to use
                    your
                    {uniswapDappSharedLogic.tradeContext!.fromToken.symbol}. You
                    only have to do this once per token per uniswap version.
                    Click here to approve the permissons.
                  </span>
                )}

                {uniswapDappSharedLogic.miningTransaction?.status ===
                  transactionStatus.waitingForConfirmation && (
                  <span>Waiting for confirmation....</span>
                )}

                {uniswapDappSharedLogic.miningTransaction?.status ===
                  transactionStatus.mining && (
                  <span>Waiting for your transaction to be mined...</span>
                )}
              </span>
            </div>
          </button>
        )}
    </div>
  );
};

export default Approval;
