// vue/src/uniswap/internal-components/approval.vue
<template>
  <button
    class="uni-ic__swap-allow uni-ic__theme-background-button"
    v-if="
      tradeContext &&
        tradeContext.approvalTransaction &&
        tradeContext.fromBalance &&
        tradeContext.fromBalance.hasEnough
    "
    :disabled="logic.transactionInProcess()"
    v-on:click="logic.approveAllowance()"
  >
    <div class="uni-ic__swap-allow-container">
      <TokenIcon
        classes="uni-ic__swap-allow-icon"
        :context="logic.inputToken.tokenImageContext"
      />

      <span
        v-if="
          miningTransaction === undefined ||
            miningTransactionStatus === TransactionStatus.rejected
        "
        >You must give the Uniswap smart contract permisson to use your
        {{ tradeContext.fromToken.symbol }}. You only have to do this once per
        token per uniswap version. Click here to approve the permissons.
      </span>

      <span
        v-if="
          miningTransactionStatus === TransactionStatus.waitingForConfirmation
        "
        >Waiting for confirmation....</span
      >
      <span v-if="miningTransactionStatus === TransactionStatus.mining"
        >Waiting for your transaction to be mined...
        <u
          ><a
            class="uni-ic__swap-allow-etherscan"
            v-on:click="logic.viewOnEtherscan()"
          >
            View tx on etherscan
          </a>
        </u>
      </span>
    </div>
  </button>
</template>

<script lang="ts">
import { default as TokenIcon } from './token-icon.vue';
import { TransactionStatus } from 'uniswap-dapp-integration-shared';
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'Approval',
  components: {
    TokenIcon,
  },
  props: [
    'logic',
    'tradeContext',
    'miningTransaction',
    'miningTransactionStatus',
  ],
  data() {
    return {
      TransactionStatus,
    };
  },
});
</script>

// react-package/package/src/components/approval.tsx
import React from 'react';
import {
  MiningTransaction,
  TradeContext,
  TransactionStatus,
  UniswapDappSharedLogic
} from 'uniswap-dapp-integration-shared';
import TokenIcon from './tokenIcon';

const Approval = ({
  uniswapDappSharedLogic,
  tradeContext, 
  miningTransaction,
  miningTransactionStatus,
}: {
  uniswapDappSharedLogic: UniswapDappSharedLogic;
  tradeContext: TradeContext | undefined;
  miningTransaction: MiningTransaction | undefined;
  miningTransactionStatus: TransactionStatus | undefined;
}): JSX.Element => {
  const transactionStatus = TransactionStatus;

  return (
    <div>
      {tradeContext?.approvalTransaction &&
        tradeContext?.fromBalance?.hasEnough && (
          <button
            className="uni-ic__swap-allow uni-ic__theme-background-button"
            onClick={() => uniswapDappSharedLogic.approveAllowance()}
            disabled={uniswapDappSharedLogic.transactionInProcess()}
          >
            <div className="uni-ic__swap-allow-container">
                <TokenIcon
                  classes="uni-ic__swap-allow-icon"
                  tokenImageContext={
                    uniswapDappSharedLogic.inputToken.tokenImageContext
                  }
                />

                {(miningTransaction === undefined ||
                  miningTransactionStatus === transactionStatus.rejected) && (
                  <span>
                    You must give the Uniswap smart contract permisson to use
                    your {tradeContext!.fromToken.symbol}. You only have to do
                    this once per token per uniswap version. Click here to
                    approve the permissons.
                  </span>
                )}

                {miningTransaction?.status ===
                  transactionStatus.waitingForConfirmation && (
                  <span>Waiting for confirmation....</span>
                )}

                {miningTransaction?.status === transactionStatus.mining && (
                  <span>Waiting for your transaction to be mined... 
                       <u
                        ><a
                          className="uni-ic__swap-allow-etherscan"
                          onClick={() => uniswapDappSharedLogic.viewOnEtherscan()}
                        >
                          View tx on etherscan
                        </a>
                      </u>
                  </span>
                )}
            </div>
          </button>
        )}
    </div>
  );
};

export default Approval;
