// react-package/package/src/components/swapQuoteInfo.tsx
import React from 'react';
import { UniswapDappSharedLogic } from 'uniswap-dapp-integration-shared';

const SwapQuoteInfo = ({
  uniswapDappSharedLogic,
}: {
  uniswapDappSharedLogic: UniswapDappSharedLogic;
}): JSX.Element => {
  return (
    <div>
      {uniswapDappSharedLogic.tradeContext && (
        <div className="uni-ic__swap-quote">
          <div className="uni-ic__swap-quote-container">
            <div className="uni-ic__swap-quote-price">
              <div
                font-size="14px"
                color="text"
                className="uni-ic__swap-quote-price-text"
                style={{ padding: '0.1rem 0.5rem 0.1rem 0.35rem' }}
              >
                Best rate on
                {uniswapDappSharedLogic.tradeContext.uniswapVersion}
              </div>
              <div
                font-size="14px"
                color="text"
                className="uni-ic__swap-quote-price-text"
                style={{
                  justifyContent: 'center',
                  alignItems: 'center',
                  display: 'flex',
                }}
              >
                1{uniswapDappSharedLogic.tradeContext!.fromToken.symbol} =
                {uniswapDappSharedLogic.workOutOneEqualTo()}
                {uniswapDappSharedLogic.tradeContext!.toToken.symbol}
                <div className="uni-ic__swap-quote-price-text-info">
                  <div
                    style={{
                      padding: '0.25rem',
                      lineHeight: '0',
                      display: 'inline-block',
                    }}
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="16"
                      height="16"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      stroke-width="2"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    >
                      <circle cx="12" cy="12" r="10"></circle>
                      <line x1="12" y1="16" x2="12" y2="12"></line>
                      <line x1="12" y1="8" x2="12.01" y2="8"></line>
                    </svg>
                  </div>

                  <div
                    className="uni-ic__tooltip-wrapper"
                    style={{
                      right: '10px',
                    }}
                  >
                    <div className="uni-ic__tooltip-container">
                      <div className="uni-ic__tooltip">
                        <div className="uni-ic__tooltip__item">
                          <div className="uni-ic__tooltip__item__title">
                            <div className="uni-ic__tooltip__item__title__content">
                              Liquidity Provider Fee
                            </div>
                          </div>
                          <div className="uni-ic__tooltip__item__value">
                            {
                              uniswapDappSharedLogic.tradeContext
                                .liquidityProviderFee
                            }
                            {
                              uniswapDappSharedLogic.tradeContext.fromToken
                                .symbol
                            }
                          </div>
                        </div>
                        <div className="uni-ic__tooltip__item">
                          <div className="uni-ic__tooltip__item__title">
                            <div className="uni-ic__tooltip__item__title__content">
                              Route
                            </div>
                          </div>
                          <div className="uni-ic__tooltip__item__value">
                            {uniswapDappSharedLogic.tradeContext.routeText}
                          </div>
                        </div>
                        {uniswapDappSharedLogic.tradeContext
                          .minAmountConvertQuote && (
                          <div className="uni-ic__tooltip__item">
                            <div className="uni-ic__tooltip__item__title">
                              <div className="uni-ic__tooltip__item__title__content">
                                Minimum received
                              </div>
                            </div>
                            <div className="uni-ic__tooltip__item__value">
                              {
                                uniswapDappSharedLogic.tradeContext
                                  .minAmountConvertQuote
                              }
                              {
                                uniswapDappSharedLogic.tradeContext.toToken
                                  .symbol
                              }
                            </div>
                          </div>
                        )}
                        {uniswapDappSharedLogic.tradeContext.maximumSent && (
                          <div className="uni-ic__tooltip__item">
                            <div className="uni-ic__tooltip__item__title">
                              <div className="uni-ic__tooltip__item__title__content">
                                Maximum sent
                              </div>
                            </div>
                            <div className="uni-ic__tooltip__item__value">
                              {uniswapDappSharedLogic.tradeContext.maximumSent}
                              {
                                uniswapDappSharedLogic.tradeContext.fromToken
                                  .symbol
                              }
                            </div>
                          </div>
                        )}
                        <div className="uni-ic__tooltip__item">
                          <div className="uni-ic__tooltip__item__title">
                            <div className="uni-ic__tooltip__item__title__content">
                              Slippage tolerance
                            </div>
                          </div>
                          <div className="uni-ic__tooltip__item__value">
                            {uniswapDappSharedLogic.uniswapPairSettings
                              .slippage * 100}
                            %
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default SwapQuoteInfo;

// angular/lib/projects/uniswap-angular/src/lib/uniswap-angular-swapper/components/swap-quote-info/swap-quote-info.component.ts
import { Component, Input } from '@angular/core';
import { UniswapDappSharedLogic } from 'uniswap-dapp-integration-shared';

@Component({
  selector: 'lib-swap-quote-info',
  templateUrl: './swap-quote-info.component.html',
  styleUrls: ['./swap-quote-info.component.scss'],
})
export class SwapQuoteInfoComponent {
  @Input() public uniswapDappSharedLogic!: UniswapDappSharedLogic;

  constructor() {}
}

<div class="uni-ic__swap-quote" *ngIf="uniswapDappSharedLogic.tradeContext">
  <div class="uni-ic__swap-quote-container">
    <div class="uni-ic__swap-quote-price">
      <div
        font-size="14px"
        color="text"
        class="uni-ic__swap-quote-price-text"
        style="padding: 0.1rem 0.5rem 0.1rem 0.35rem"
      >
        Best rate on
        {{ uniswapDappSharedLogic.tradeContext.uniswapVersion }}
      </div>
      <div
        font-size="14px"
        color="text"
        class="uni-ic__swap-quote-price-text"
        style="justify-content: center; align-items: center; display: flex"
      >
        1
        {{ uniswapDappSharedLogic.tradeContext.fromToken.symbol }} =
        {{ uniswapDappSharedLogic.workOutOneEqualTo() }}
        {{ uniswapDappSharedLogic.tradeContext.toToken.symbol }}
        <div class="uni-ic__swap-quote-price-text-info">
          <div style="display: inline-block; line-height: 0; padding: 0.25rem">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="sc-gHboQg lftHvR"
            >
              <circle cx="12" cy="12" r="10"></circle>
              <line x1="12" y1="16" x2="12" y2="12"></line>
              <line x1="12" y1="8" x2="12.01" y2="8"></line>
            </svg>
          </div>

          <div
            class="uni-ic__tooltip-wrapper"
            data-popper-reference-hidden="false"
            data-popper-escaped="false"
            data-popper-placement="left"
            style="
              position: fixed;
              inset: 0px 0px auto auto;
              transform: translate(-1480px, 253px);
            "
          >
            <div class="uni-ic__tooltip-container">
              <div class="uni-ic__tooltip">
                <div class="uni-ic__tooltip__item">
                  <div class="uni-ic__tooltip__item__title">
                    <div class="uni-ic__tooltip__item__title__content">
                      Liquidity Provider Fee
                    </div>
                  </div>
                  <div class="uni-ic__tooltip__item__value">
                    {{
                      uniswapDappSharedLogic.tradeContext.liquidityProviderFee
                    }}
                    {{ uniswapDappSharedLogic.tradeContext.fromToken.symbol }}
                  </div>
                </div>
                <div class="uni-ic__tooltip__item">
                  <div class="uni-ic__tooltip__item__title">
                    <div class="uni-ic__tooltip__item__title__content">
                      Route
                    </div>
                  </div>
                  <div class="uni-ic__tooltip__item__value">
                    {{ uniswapDappSharedLogic.tradeContext.routeText }}
                  </div>
                </div>
                <div
                  class="uni-ic__tooltip__item"
                  *ngIf="
                    uniswapDappSharedLogic.tradeContext.minAmountConvertQuote
                  "
                >
                  <div class="uni-ic__tooltip__item__title">
                    <div class="uni-ic__tooltip__item__title__content">
                      Minimum received
                    </div>
                  </div>
                  <div class="uni-ic__tooltip__item__value">
                    {{
                      uniswapDappSharedLogic.tradeContext.minAmountConvertQuote
                    }}
                    {{ uniswapDappSharedLogic.tradeContext.toToken.symbol }}
                  </div>
                </div>
                <div
                  class="uni-ic__tooltip__item"
                  *ngIf="uniswapDappSharedLogic.tradeContext.maximumSent"
                >
                  <div class="uni-ic__tooltip__item__title">
                    <div class="uni-ic__tooltip__item__title__content">
                      Maximum sent
                    </div>
                  </div>
                  <div class="uni-ic__tooltip__item__value">
                    {{ uniswapDappSharedLogic.tradeContext.maximumSent }}
                    {{ uniswapDappSharedLogic.tradeContext.fromToken.symbol }}
                  </div>
                </div>
                <div class="uni-ic__tooltip__item">
                  <div class="uni-ic__tooltip__item__title">
                    <div class="uni-ic__tooltip__item__title__content">
                      Slippage tolerance
                    </div>
                  </div>
                  <div class="uni-ic__tooltip__item__value">
                    {{
                      uniswapDappSharedLogic.uniswapPairSettings.slippage * 100
                    }}%
                  </div>
                </div>
              </div>
            </div>
            <div
              class="uni-ic__tooltip__arrow"
              style="
                position: absolute;
                top: 0px;
                transform: translate(0px, 51px);
              "
            ></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
