// react-package/package/src/components/tokensModal.tsx
import React from 'react';
import {
  SelectTokenActionFrom,
  SwapSwitchResponse,
  UniswapDappSharedLogic,
  Utils as UniswapUtils,
} from 'uniswap-dapp-integration-shared';

const TokensModal = ({
  uniswapDappSharedLogic,
  switchSwapCompleted,
}: {
  uniswapDappSharedLogic: UniswapDappSharedLogic;
  switchSwapCompleted: (swapSwitchResponse: SwapSwitchResponse) => void;
}): JSX.Element => {
  const [searchToken, setSearchToken] = React.useState('');

  const searchForToken = async (search: string) => {
    setSearchToken(search);
    uniswapDappSharedLogic.searchToken(search);
  };

  const changeSelectToken = async (contractAddress: string) => {
    switch (uniswapDappSharedLogic.selectorOpenFrom) {
      case SelectTokenActionFrom.input:
        if (
          uniswapDappSharedLogic.tradeContext?.fromToken.contractAddress ===
          contractAddress
        ) {
          uniswapDappSharedLogic.hideTokenSelector();
          return;
        }

        if (
          uniswapDappSharedLogic.tradeContext?.toToken.contractAddress ===
          contractAddress
        ) {
          const swapResponse = await uniswapDappSharedLogic.swapSwitch();
          switchSwapCompleted(swapResponse);
          uniswapDappSharedLogic.hideTokenSelector();
          return;
        }
        await uniswapDappSharedLogic.changeToken(contractAddress);
        return;
      case SelectTokenActionFrom.output:
        if (
          uniswapDappSharedLogic.tradeContext?.toToken.contractAddress ===
          contractAddress
        ) {
          uniswapDappSharedLogic.hideTokenSelector();
          return;
        }

        if (
          uniswapDappSharedLogic.tradeContext?.fromToken.contractAddress ===
          contractAddress
        ) {
          const swapResponse = await uniswapDappSharedLogic.swapSwitch();
          switchSwapCompleted(swapResponse);
          uniswapDappSharedLogic.hideTokenSelector();
          return;
        }

        await uniswapDappSharedLogic.changeToken(contractAddress);
    }
  };

  const utils = UniswapUtils;

  return (
    <div>
      {uniswapDappSharedLogic.supportedNetwork && (
        <div id="uni-ic__modal-token" className="uni-ic__modal">
          <div className="uni-ic__modal__content uni-ic__modal-tokens uni-ic__theme-background">
            <span
              className="uni-ic__modal__close"
              onClick={() => uniswapDappSharedLogic.hideTokenSelector()}
            >
              &times;
            </span>
            <p className="uni-ic__modal-tokens-title">Select a token</p>
            <div className="uni-ic__modal-tokens-search">
              <input
                type="text"
                placeholder="Search name or paste address"
                className="uni-ic__modal-tokens-search__input"
                value={searchToken}
                onChange={(e) => {
                  searchForToken(e.target.value);
                }}
              />
            </div>
            <div style={{ flex: '1 1 0%', position: 'relative' }}>
              <div style={{ overflow: 'visible', height: '0px' }}>
                <div
                  style={{
                    position: 'relative',
                    height: '210px',
                    width: '100%',
                    overflow: 'auto',
                    willChange: 'transform',
                    direction: 'ltr',
                  }}
                >
                  <div style={{ height: '100%', width: '100%' }}>
                    {uniswapDappSharedLogic.supportedTokenBalances.map(
                      (token) => (
                        <div
                          key={token.name}
                          onClick={() =>
                            changeSelectToken(token.contractAddress)
                          }
                          className={`uni-ic__modal-tokens-item-container ${
                            (token.contractAddress ===
                              uniswapDappSharedLogic.inputToken
                                .contractAddress &&
                              uniswapDappSharedLogic.selectorOpenFrom ===
                                'input') ||
                            (token.contractAddress ===
                              uniswapDappSharedLogic.outputToken
                                ?.contractAddress &&
                              uniswapDappSharedLogic.selectorOpenFrom ===
                                'output')
                              ? 'selected'
                              : ''
                          }`}
                        >
                          {token.canShow && (
                            <div className="uni-ic__modal-tokens-item">
                              {!token.tokenImageContext.isSvg && (
                                <img
                                  src={token.tokenImageContext.image}
                                  className="uni-ic__modal-tokens-item-icon"
                                />
                              )}

                              {token.tokenImageContext.isSvg && (
                                <div className="uni-ic__modal-tokens-item-icon">
                                  {token.tokenImageContext.image}
                                </div>
                              )}

                              <div className="uni-ic__modal-tokens-item-content">
                                <div className="uni-ic__modal-tokens-item-content-symbol">
                                  {token.symbol}
                                </div>
                                <div className="uni-ic__modal-tokens-item-content-name">
                                  {token.name}
                                </div>
                              </div>

                              <span></span>

                              <div
                                className="uni-ic__modal-tokens-item-balance-content"
                                style={{ justifySelf: 'flex-end' }}
                              >
                                <div className="uni-ic__modal-tokens-item-balance-content-value">
                                  {utils.toPrecision(token.balance)}
                                </div>
                              </div>
                            </div>
                          )}
                        </div>
                      ),
                    )}
                  </div>
                </div>
              </div>
              <div className="resize-triggers">
                <div className="expand-trigger">
                  <div style={{ width: '419px', height: '211px' }}></div>
                </div>
                <div className="contract-trigger"></div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default TokensModal;

// angular/lib/projects/uniswap-angular/src/lib/uniswap-angular-swapper/components/tokens-modal/tokens-modal.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import {
  SelectTokenActionFrom,
  SwapSwitchResponse,
  UniswapDappSharedLogic,
  Utils as UniswapUtils,
} from 'uniswap-dapp-integration-shared';

@Component({
  selector: 'lib-tokens-modal',
  templateUrl: './tokens-modal.component.html',
  styleUrls: ['./tokens-modal.component.scss'],
})
export class TokensModalComponent {
  @Input() public uniswapDappSharedLogic!: UniswapDappSharedLogic;
  @Output() public switchSwapCompleted = new EventEmitter<SwapSwitchResponse>();

  public utils = UniswapUtils;
  public searchToken: string | undefined;
  constructor() {}

  /**
   * Change select token
   * @param contractAddress The contractAddress
   */
  public async changeSelectToken(contractAddress: string): Promise<void> {
    switch (this.uniswapDappSharedLogic.selectorOpenFrom) {
      case SelectTokenActionFrom.input:
        if (
          this.uniswapDappSharedLogic.tradeContext?.fromToken
            .contractAddress === contractAddress
        ) {
          this.uniswapDappSharedLogic.hideTokenSelector();
          return;
        }

        if (
          this.uniswapDappSharedLogic.tradeContext?.toToken.contractAddress ===
          contractAddress
        ) {
          const swapResponse = await this.uniswapDappSharedLogic.swapSwitch();
          this.switchSwapCompleted.emit(swapResponse);
          this.uniswapDappSharedLogic.hideTokenSelector();
          return;
        }
        await this.uniswapDappSharedLogic.changeToken(contractAddress);
        return;
      case SelectTokenActionFrom.output:
        if (
          this.uniswapDappSharedLogic.tradeContext?.toToken.contractAddress ===
          contractAddress
        ) {
          this.uniswapDappSharedLogic.hideTokenSelector();
          return;
        }

        if (
          this.uniswapDappSharedLogic.tradeContext?.fromToken
            .contractAddress === contractAddress
        ) {
          const swapResponse = await this.uniswapDappSharedLogic.swapSwitch();
          this.switchSwapCompleted.emit(swapResponse);
          this.uniswapDappSharedLogic.hideTokenSelector();
          return;
        }
        await this.uniswapDappSharedLogic.changeToken(contractAddress);
    }
  }
}

<div
  id="uni-ic__modal-token"
  class="uni-ic__modal"
  *ngIf="uniswapDappSharedLogic.supportedNetwork"
>
  <div
    class="uni-ic__modal__content uni-ic__modal-tokens uni-ic__theme-background"
  >
    <span
      class="uni-ic__modal__close"
      (click)="uniswapDappSharedLogic.hideTokenSelector()"
      >&times;</span
    >
    <p class="uni-ic__modal-tokens-title">Select a token</p>
    <div class="uni-ic__modal-tokens-search">
      <input
        type="text"
        placeholder="Search name or paste address"
        autocomplete="off"
        class="uni-ic__modal-tokens-search__input"
        [ngModel]="searchToken"
        (ngModelChange)="uniswapDappSharedLogic.searchToken($event)"
      />
    </div>

    <div style="flex: 1 1 0%; position: relative">
      <div style="overflow: visible; height: 0px">
        <div
          style="
            position: relative;
            height: 210px;
            width: 100%;
            overflow: auto;
            will-change: transform;
            direction: ltr;
          "
        >
          <div style="height: 100%; width: 100%">
            <div
              *ngFor="
                let token of uniswapDappSharedLogic.supportedTokenBalances
              "
              (click)="changeSelectToken(token.contractAddress)"
              class="uni-ic__modal-tokens-item-container"
              [ngClass]="{
                selected:
                  (token.contractAddress ===
                    uniswapDappSharedLogic.inputToken.contractAddress &&
                    uniswapDappSharedLogic.selectorOpenFrom === 'input') ||
                  (token.contractAddress ===
                    uniswapDappSharedLogic.outputToken?.contractAddress &&
                    uniswapDappSharedLogic.selectorOpenFrom === 'output')
              }"
            >
              <div class="uni-ic__modal-tokens-item" *ngIf="token.canShow">
                <img
                  *ngIf="!token.tokenImageContext.isSvg"
                  [src]="token.tokenImageContext.image"
                  class="uni-ic__modal-tokens-item-icon"
                />
                <div
                  *ngIf="token.tokenImageContext.isSvg"
                  class="uni-ic__modal-tokens-item-icon"
                  [innerHTML]="token.tokenImageContext.image | safe"
                ></div>

                <div class="uni-ic__modal-tokens-item-content">
                  <div class="uni-ic__modal-tokens-item-content-symbol">
                    {{ token.symbol }}
                  </div>
                  <div class="uni-ic__modal-tokens-item-content-name">
                    {{ token.name }}
                  </div>
                </div>
                <span></span>
                <div
                  class="uni-ic__modal-tokens-item-balance-content"
                  style="justify-self: flex-end"
                >
                  <div class="uni-ic__modal-tokens-item-balance-content-value">
                    {{ utils.toPrecision(token.balance) }}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="resize-triggers">
        <div class="expand-trigger">
          <div style="width: 419px; height: 211px"></div>
        </div>
        <div class="contract-trigger"></div>
      </div>
    </div>
  </div>
</div>
